export type EditorialCropBehavior = 'cover' | 'contain';
export type EditorialViewport = 'desktop' | 'mobile';
export type EditorialUsageFrequency = 'single' | 'limited-reuse';
export type EditorialReplacementStatus = 'active' | 'reserved';

interface EditorialAssetRecord {
  src: string;
  title: string;
}

export const editorialAssetCatalog = {
  'AF-10595': { src: '/Highlights/AF-10595.jpg', title: 'Studio editorial portrait in green print' },
  'AF-10611': { src: '/Highlights/AF-10611.jpg', title: 'Close portrait with orange sunglasses and green print' },
  'AF-10615': { src: '/Highlights/AF-10615.jpg', title: 'Fashion portrait against warm backdrop' },
  'AF-10674': { src: '/Highlights/AF-10674.jpg', title: 'Close portrait with floral earrings and orchid detail' },
  'AF-10679': { src: '/Highlights/AF-10679.jpg', title: 'Campaign portrait from the highlights collection' },
  'AF-10687': { src: '/Highlights/AF-10687.jpg', title: 'Styled portrait with accessories' },
  'AF-10697': { src: '/Highlights/AF-10697.jpg', title: 'Editorial portrait in studio lighting' },
  'AF-10714': { src: '/Highlights/AF-10714.jpg', title: 'Full look in a flowing green print silhouette' },
  'AF-10721': { src: '/Highlights/AF-10721.jpg', title: 'Statement green editorial silhouette indoors' },
  'AF-10800': { src: '/Highlights/AF-10800.jpg', title: 'Full-length brown look against a coral backdrop' },
  'AF-10814': { src: '/Highlights/AF-10814.jpg', title: 'Studio fashion pose from the coral set' },
  'AF-10841': { src: '/Highlights/AF-10841.jpg', title: 'Editorial fashion campaign portrait' },
  'AF-10851': { src: '/Highlights/AF-10851.jpg', title: 'Color-rich campaign portrait' },
  'AF-10885': { src: '/Highlights/AF-10885.jpg', title: 'Group portrait in the campaign studio' },
  'AF-10902': { src: '/Highlights/AF-10902.jpg', title: 'Two-model editorial portrait' },
  'AF-10955': { src: '/Highlights/AF-10955.jpg', title: 'Campaign image with layered styling' },
  'AF-10957': { src: '/Highlights/AF-10957.jpg', title: 'Studio portrait from the ribbon look series' },
  'AF-10974': { src: '/Highlights/AF-10974.jpg', title: 'Two-model ribbon look on pink backdrop' },
  'AF-10976': { src: '/Highlights/AF-10976.jpg', title: 'Campaign image from the pink backdrop set' },
  'AF-10990': { src: '/Highlights/AF-10990.jpg', title: 'Ribbon-look portrait from the studio series' },
  'AF-10996': { src: '/Highlights/AF-10996.jpg', title: 'Fashion portrait with statement styling' },
  'AF-11009': { src: '/Highlights/AF-11009.jpg', title: 'Editorial portrait from the campaign studio' },
  'AF-11016': { src: '/Highlights/AF-11016.jpg', title: 'Portrait highlighting styling details' },
  'AF-11022': { src: '/Highlights/AF-11022.jpg', title: 'Campaign portrait with warm-toned styling' },
  'AF-11026': { src: '/Highlights/AF-11026.jpg', title: 'Editorial look from the highlights campaign' },
  'AF-11039': { src: '/Highlights/AF-11039.jpg', title: 'Studio portrait with contemporary silhouette' },
  'AF-11040': { src: '/Highlights/AF-11040.jpg', title: 'Campaign close-up from the highlights folder' },
  'AF-11057': { src: '/Highlights/AF-11057.jpg', title: 'Editorial fashion still from the campaign' },
  'AF-11061': { src: '/Highlights/AF-11061.jpg', title: 'Three-model community campaign portrait' },
  'AF-11064': { src: '/Highlights/AF-11064.jpg', title: 'Studio group styling moment' },
  'AF-11072': { src: '/Highlights/AF-11072.jpg', title: 'Bold fashion portrait on pink backdrop' },
  'AF-11081': { src: '/Highlights/AF-11081.jpg', title: 'Mustard editorial look with ribbon skirt' },
} as const satisfies Record<string, EditorialAssetRecord>;

export type EditorialAssetId = keyof typeof editorialAssetCatalog;

interface EditorialPlacementAsset {
  assetId: EditorialAssetId;
  cropBehavior: EditorialCropBehavior;
  objectPosition: string;
}

export interface EditorialImagePlacement {
  page: string;
  section: string;
  primaryOwner: string;
  desktopAsset: EditorialPlacementAsset;
  mobileAsset?: EditorialPlacementAsset;
  alt: string;
  approvedSecondaryUses: string[];
  usageFrequency: EditorialUsageFrequency;
  replacementStatus: EditorialReplacementStatus;
}

export const editorialImagePlacements = {
  'home.hero': {
    page: 'home',
    section: 'hero',
    primaryOwner: 'Homepage hero campaign',
    desktopAsset: { assetId: 'AF-10974', cropBehavior: 'cover', objectPosition: 'center 28%' },
    mobileAsset: { assetId: 'AF-11061', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'FabTops campaign portrait showcasing two statement looks against a pink studio backdrop.',
    approvedSecondaryUses: ['Search promo reuse only if the home hero changes later'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'home.category.tops': {
    page: 'home',
    section: 'category-navigation',
    primaryOwner: 'Homepage category tile for Tops',
    desktopAsset: { assetId: 'AF-10721', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'Model wearing a green FabTops silhouette with a dramatic draped shape.',
    approvedSecondaryUses: ['Collection landing fallback if a dedicated tile is unavailable'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'home.category.sets': {
    page: 'home',
    section: 'category-navigation',
    primaryOwner: 'Homepage category tile for Sets',
    desktopAsset: { assetId: 'AF-10902', cropBehavior: 'cover', objectPosition: 'left 26% top' },
    alt: 'FabTops coordinated look with black bodice styling and ribbon-detail skirt.',
    approvedSecondaryUses: ['None'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'home.category.dresses': {
    page: 'home',
    section: 'category-navigation',
    primaryOwner: 'Homepage category tile for Dresses',
    desktopAsset: { assetId: 'AF-10800', cropBehavior: 'cover', objectPosition: 'center 20%' },
    alt: 'Model in a brown FabTops dress with sculptural ruffle accents.',
    approvedSecondaryUses: ['Collections archive storytelling if required'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'home.category.accessories': {
    page: 'home',
    section: 'category-navigation',
    primaryOwner: 'Homepage category tile for Accessories',
    desktopAsset: { assetId: 'AF-10611', cropBehavior: 'cover', objectPosition: 'center 24%' },
    alt: 'Close-up of FabTops styling featuring sunglasses, floral accessories, and gold jewelry.',
    approvedSecondaryUses: ['Community portrait crop if needed in future'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'home.category.archive': {
    page: 'home',
    section: 'category-navigation',
    primaryOwner: 'Homepage category tile for Archive',
    desktopAsset: { assetId: 'AF-11081', cropBehavior: 'cover', objectPosition: 'center top' },
    alt: 'Mustard FabTops archival look with ribbon detailing against a pink backdrop.',
    approvedSecondaryUses: ['Archive page storytelling'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'home.new-collection.primary': {
    page: 'home',
    section: 'new-collection-showcase',
    primaryOwner: 'Homepage new collection primary visual',
    desktopAsset: { assetId: 'AF-10714', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'Green FabTops statement dress displayed in a composed editorial interior.',
    approvedSecondaryUses: ['Sustainability story if the homepage module is retired'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'home.new-collection.detail': {
    page: 'home',
    section: 'new-collection-showcase',
    primaryOwner: 'Homepage new collection detail card',
    desktopAsset: { assetId: 'AF-10674', cropBehavior: 'cover', objectPosition: 'center 24%' },
    alt: 'Close-up FabTops beauty portrait highlighting statement earrings and floral styling.',
    approvedSecondaryUses: ['Search curated promo card'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'home.circle-banner': {
    page: 'home',
    section: 'circle-banner',
    primaryOwner: 'Homepage Fab Babe Circle banner',
    desktopAsset: { assetId: 'AF-10885', cropBehavior: 'cover', objectPosition: 'center 18%' },
    mobileAsset: { assetId: 'AF-11064', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'FabTops community campaign portrait celebrating the Fab Babe Circle.',
    approvedSecondaryUses: ['Circle page hero on smaller screens'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'home.community.amara': {
    page: 'home',
    section: 'community-social-proof',
    primaryOwner: 'Homepage community testimonial for Amara',
    desktopAsset: { assetId: 'AF-10615', cropBehavior: 'cover', objectPosition: 'center 20%' },
    alt: 'FabTops community portrait with floral earrings and polished editorial styling.',
    approvedSecondaryUses: ['Small avatar crop only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'home.community.zainab': {
    page: 'home',
    section: 'community-social-proof',
    primaryOwner: 'Homepage community testimonial for Zainab',
    desktopAsset: { assetId: 'AF-10687', cropBehavior: 'cover', objectPosition: 'center 24%' },
    alt: 'FabTops community portrait with sunglasses, orchid accents, and layered jewelry.',
    approvedSecondaryUses: ['Accessory storytelling crop only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'home.community.blessing': {
    page: 'home',
    section: 'community-social-proof',
    primaryOwner: 'Homepage community testimonial for Blessing',
    desktopAsset: { assetId: 'AF-10595', cropBehavior: 'cover', objectPosition: 'center 22%' },
    alt: 'FabTops portrait featuring green print styling and a poised side profile.',
    approvedSecondaryUses: ['None'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'home.sustainability-preview': {
    page: 'home',
    section: 'sustainability-preview',
    primaryOwner: 'Homepage sustainability preview image',
    desktopAsset: { assetId: 'AF-11040', cropBehavior: 'cover', objectPosition: 'center 22%' },
    alt: 'FabTops editorial image highlighting expressive craftsmanship and fabric movement.',
    approvedSecondaryUses: ['Sustainability detail only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'about.hero': {
    page: 'about',
    section: 'hero',
    primaryOwner: 'About page hero image',
    desktopAsset: { assetId: 'AF-11039', cropBehavior: 'cover', objectPosition: 'center 20%' },
    alt: 'FabTops editorial portrait reflecting the brand story and modern femininity.',
    approvedSecondaryUses: ['None'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'collections.grid.tops': {
    page: 'collections',
    section: 'collection-grid',
    primaryOwner: 'Collections grid tile for Tops',
    desktopAsset: { assetId: 'AF-11022', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'Green FabTops silhouette presented as a signature tops collection image.',
    approvedSecondaryUses: ['Collection hero for tops'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.grid.sets': {
    page: 'collections',
    section: 'collection-grid',
    primaryOwner: 'Collections grid tile for Sets',
    desktopAsset: { assetId: 'AF-10955', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'Two-model FabTops editorial look representing coordinated sets.',
    approvedSecondaryUses: ['Collection hero for sets'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.grid.dresses': {
    page: 'collections',
    section: 'collection-grid',
    primaryOwner: 'Collections grid tile for Dresses',
    desktopAsset: { assetId: 'AF-10814', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'FabTops dress look posed against a vibrant coral backdrop.',
    approvedSecondaryUses: ['Collection hero for dresses'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.grid.accessories': {
    page: 'collections',
    section: 'collection-grid',
    primaryOwner: 'Collections grid tile for Accessories',
    desktopAsset: { assetId: 'AF-10674', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'FabTops styling portrait emphasizing statement accessories and detail work.',
    approvedSecondaryUses: ['Search promo fallback'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.hero.tops': {
    page: 'collection-detail',
    section: 'hero',
    primaryOwner: 'Collection hero for tops',
    desktopAsset: { assetId: 'AF-10721', cropBehavior: 'cover', objectPosition: 'center 16%' },
    mobileAsset: { assetId: 'AF-10721', cropBehavior: 'cover', objectPosition: 'center 10%' },
    alt: 'FabTops tops collection hero featuring an expressive green silhouette.',
    approvedSecondaryUses: ['Grid tile reuse only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.hero.sets': {
    page: 'collection-detail',
    section: 'hero',
    primaryOwner: 'Collection hero for sets',
    desktopAsset: { assetId: 'AF-10902', cropBehavior: 'cover', objectPosition: 'center 14%' },
    mobileAsset: { assetId: 'AF-10902', cropBehavior: 'cover', objectPosition: 'center 10%' },
    alt: 'FabTops sets collection hero with coordinated editorial styling.',
    approvedSecondaryUses: ['Grid tile reuse only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.hero.dresses': {
    page: 'collection-detail',
    section: 'hero',
    primaryOwner: 'Collection hero for dresses',
    desktopAsset: { assetId: 'AF-10800', cropBehavior: 'cover', objectPosition: 'center 14%' },
    mobileAsset: { assetId: 'AF-10800', cropBehavior: 'cover', objectPosition: 'center 10%' },
    alt: 'FabTops dresses collection hero with sculptural dress styling.',
    approvedSecondaryUses: ['Grid tile reuse only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.hero.accessories': {
    page: 'collection-detail',
    section: 'hero',
    primaryOwner: 'Collection hero for accessories',
    desktopAsset: { assetId: 'AF-10611', cropBehavior: 'cover', objectPosition: 'center 22%' },
    mobileAsset: { assetId: 'AF-10611', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'FabTops accessories collection hero centered on styling details, eyewear, and jewelry.',
    approvedSecondaryUses: ['Community avatar crop only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.hero.archive': {
    page: 'collection-detail',
    section: 'hero',
    primaryOwner: 'Collection hero for archive',
    desktopAsset: { assetId: 'AF-11081', cropBehavior: 'cover', objectPosition: 'center 14%' },
    mobileAsset: { assetId: 'AF-11081', cropBehavior: 'cover', objectPosition: 'center 10%' },
    alt: 'FabTops archive hero spotlighting a memorable ribbon-detailed look.',
    approvedSecondaryUses: ['Archive grid storytelling only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'collections.hero.new-arrivals': {
    page: 'collection-detail',
    section: 'hero',
    primaryOwner: 'Collection hero for new arrivals',
    desktopAsset: { assetId: 'AF-11061', cropBehavior: 'cover', objectPosition: 'center 16%' },
    mobileAsset: { assetId: 'AF-11061', cropBehavior: 'cover', objectPosition: 'center 12%' },
    alt: 'FabTops new arrivals campaign featuring the latest collection in a group portrait.',
    approvedSecondaryUses: ['Circle storytelling if needed'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'archive.item.1': {
    page: 'archive',
    section: 'archive-grid',
    primaryOwner: 'Archive item 1',
    desktopAsset: { assetId: 'AF-11081', cropBehavior: 'cover', objectPosition: 'center 16%' },
    alt: 'Archived FabTops look in mustard with ribbon-detail skirt styling.',
    approvedSecondaryUses: ['Archive hero crop only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'archive.item.2': {
    page: 'archive',
    section: 'archive-grid',
    primaryOwner: 'Archive item 2',
    desktopAsset: { assetId: 'AF-10800', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'Archived FabTops brown dress with ruffle details against a vivid backdrop.',
    approvedSecondaryUses: ['None'],
    usageFrequency: 'single',
    replacementStatus: 'active',
  },
  'archive.item.3': {
    page: 'archive',
    section: 'archive-grid',
    primaryOwner: 'Archive item 3',
    desktopAsset: { assetId: 'AF-10974', cropBehavior: 'cover', objectPosition: 'right 28% top' },
    alt: 'Archived FabTops ribbon-detail silhouette styled in the studio.',
    approvedSecondaryUses: ['Home hero desktop only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'archive.item.4': {
    page: 'archive',
    section: 'archive-grid',
    primaryOwner: 'Archive item 4',
    desktopAsset: { assetId: 'AF-10714', cropBehavior: 'cover', objectPosition: 'center 20%' },
    alt: 'Archived FabTops green print silhouette displayed in an editorial interior.',
    approvedSecondaryUses: ['Sustainability preview only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'archive.item.5': {
    page: 'archive',
    section: 'archive-grid',
    primaryOwner: 'Archive item 5',
    desktopAsset: { assetId: 'AF-10721', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'Archived FabTops green statement silhouette with dramatic drape.',
    approvedSecondaryUses: ['Collections tops only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'archive.item.6': {
    page: 'archive',
    section: 'archive-grid',
    primaryOwner: 'Archive item 6',
    desktopAsset: { assetId: 'AF-10902', cropBehavior: 'cover', objectPosition: 'right 28% top' },
    alt: 'Archived FabTops evening look from a two-model studio campaign.',
    approvedSecondaryUses: ['Collections sets only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'sustainability.hero': {
    page: 'sustainability',
    section: 'hero',
    primaryOwner: 'Sustainability hero',
    desktopAsset: { assetId: 'AF-10714', cropBehavior: 'cover', objectPosition: 'center 22%' },
    mobileAsset: { assetId: 'AF-10714', cropBehavior: 'cover', objectPosition: 'center 10%' },
    alt: 'FabTops look photographed in a calm editorial interior to support the sustainability story.',
    approvedSecondaryUses: ['Home preview only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'sustainability.story.packaging': {
    page: 'sustainability',
    section: 'story-packaging',
    primaryOwner: 'Sustainability packaging story',
    desktopAsset: { assetId: 'AF-10674', cropBehavior: 'cover', objectPosition: 'center 20%' },
    alt: 'FabTops editorial detail shot used to support the brand packaging and craftsmanship story.',
    approvedSecondaryUses: ['Search curated promo only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'sustainability.story.ethical': {
    page: 'sustainability',
    section: 'story-ethical',
    primaryOwner: 'Sustainability ethical sourcing story',
    desktopAsset: { assetId: 'AF-11061', cropBehavior: 'cover', objectPosition: 'center 14%' },
    alt: 'FabTops group portrait representing community, collaboration, and ethical partnership.',
    approvedSecondaryUses: ['Circle hero mobile only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'circle.hero': {
    page: 'circle',
    section: 'hero',
    primaryOwner: 'Circle page hero',
    desktopAsset: { assetId: 'AF-11061', cropBehavior: 'cover', objectPosition: 'center 16%' },
    mobileAsset: { assetId: 'AF-10885', cropBehavior: 'cover', objectPosition: 'center 18%' },
    alt: 'FabTops community campaign portrait introducing the Fab Babe Circle membership.',
    approvedSecondaryUses: ['Homepage circle banner'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'circle.philosophy': {
    page: 'circle',
    section: 'philosophy',
    primaryOwner: 'Circle philosophy image',
    desktopAsset: { assetId: 'AF-10611', cropBehavior: 'cover', objectPosition: 'center 20%' },
    alt: 'FabTops styling portrait with sunglasses and statement jewelry for the Circle philosophy section.',
    approvedSecondaryUses: ['Accessories hero only'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
  'search-modal.featured-highlight': {
    page: 'search-modal',
    section: 'curated-edit',
    primaryOwner: 'Search modal curated promo card',
    desktopAsset: { assetId: 'AF-10674', cropBehavior: 'cover', objectPosition: 'center 22%' },
    alt: 'FabTops curated editorial portrait used in the search modal featured edit.',
    approvedSecondaryUses: ['New collection detail card'],
    usageFrequency: 'limited-reuse',
    replacementStatus: 'active',
  },
} as const satisfies Record<string, EditorialImagePlacement>;

export type EditorialPlacementId = keyof typeof editorialImagePlacements;

export interface ResolvedEditorialImage extends Omit<EditorialImagePlacement, 'desktopAsset' | 'mobileAsset'> {
  placementId: EditorialPlacementId;
  assetId: EditorialAssetId;
  src: string;
  title: string;
  cropBehavior: EditorialCropBehavior;
  objectPosition: string;
}

export function getEditorialImage(
  placementId: EditorialPlacementId,
  viewport: EditorialViewport = 'desktop',
): ResolvedEditorialImage {
  const placement: EditorialImagePlacement = editorialImagePlacements[placementId];
  const assetConfig = viewport === 'mobile' && placement.mobileAsset ? placement.mobileAsset : placement.desktopAsset;
  const asset = editorialAssetCatalog[assetConfig.assetId];

  return {
    placementId,
    page: placement.page,
    section: placement.section,
    primaryOwner: placement.primaryOwner,
    alt: placement.alt,
    approvedSecondaryUses: [...placement.approvedSecondaryUses],
    usageFrequency: placement.usageFrequency,
    replacementStatus: placement.replacementStatus,
    assetId: assetConfig.assetId,
    src: asset.src,
    title: asset.title,
    cropBehavior: assetConfig.cropBehavior,
    objectPosition: assetConfig.objectPosition,
  };
}
